# Generated by Django 4.2.7 on 2024-05-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_inventory_items', models.IntegerField(default=0)),
                ('total_price_catalogue_items', models.IntegerField(default=0)),
                ('total_production_records', models.IntegerField(default=0)),
                ('total_customers', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_reports', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dashboard Metrics',
                'verbose_name_plural': 'Dashboard Metrics',
            },
        ),
    ]
