# Generated by Django 4.2.7 on 2024-05-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale',
            field=models.CharField(max_length=100),
        ),
    ]
