# Generated by Django 4.2.7 on 2024-05-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesperson', '0001_initial'),
        ('invoice', '0003_invoice_amount_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesperson.salesperson'),
        ),
    ]
